version: "3"
services:
  backend:
    build: .
    ports:
      - 10520:10520
    environment:
      - NODE_ENV=production
      - MONGODB_CXN_STRING_DEV=mongodb://admin:secret@mongodb:27017
      - MONGODB_CXN_STRING_PROD=mongodb://admin:secret@mongodb:27017
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
